version: "3"
services:
  backend:
    container_name: InTour_backend
    build: .
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - .:/src

  db:
    container_name: InTour_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/var/mongo/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PWD}
      - MONGO_INITDB_DATABASE=inTour

volumes:  
  mongo_data:
    driver: local
